### ISSUE TITLE
BREAKS existing App Store apps!

### ISSUE THREAD

**Issue by JacobSyndeo** [objectiveSee/DRKonamiCode#10]
My app, which was last updated on App Store in 2015, suddenly stopped installing on anyone's iPhones. Both myself and Apple were stumped by this, but I rolled my code back and tried to build again… and it builds successfully, but the simulator shows the same "Could not install" error message that real devices have been showing!

But on macOS, we have a console, and its log says:

> -[IXSCoordinatedAppInstall _onQueue_acquireAssertionAndDoInstall]_block_invoke: Installation for <IXSCoordinatedAppInstall<0x7fb582613300> identifier:com.BronyNet.BronyTunes uuid:3034B569-531C-4D72-8569-F4B994F9E643 intent:IXCoordinatorIntentInitiating creator/appDRI:InstallCoordination Simple SPI userInitiated:N state:IXAppCoordinationStateWaitingForInstall> failed: Error Domain=MIInstallerErrorDomain Code=12 "Bundle at path /Users/jacobpritchett/Library/Developer/CoreSimulator/Devices/C00F95AD-8D66-480B-B28F-C65CC8A285EA/data/Library/Caches/com.apple.mobile.installd.staging/temp.BnDO22/extracted/BronyTunes.app/Frameworks/DRKonamiCode.framework did not have a CFBundleIdentifier in its Info.plist" UserInfo={LegacyErrorString=MissingBundleIdentifier, FunctionName=-[MIBundle _validateWithError:], SourceFileLine=45, NSLocalizedDescription=Bundle at path /Users/jacobpritchett/Library/Developer/CoreSimulator/Devices/C00F95AD-8D66-480B-B28F-C65CC8A285EA/data/Library/Caches/com.apple.mobile.installd.staging/temp.BnDO22/e

So something's going very wrong here, and it seems to point back to DRKonamiCode.

**Comment by objectiveSee** [comment]
Feel free to let me know of any changes you need to make to this repo @JacobSyndeo

**Comment by JacobSyndeo** [comment]
Unfortunately, I don't know which changes need to be made. All I know is that when I removed it, the app installed correctly again.

**Comment by objectiveSee** [comment]
Bummer :/
